# Data
path: /content/drive/My Drive/nic_project/datasets/corner_det
train: images/train  # train images (relative to 'path')
val: images/val  # val images (relative to 'path')


# Classes
names:
  0: top_left
  1: top_right
  2: bottom_right
  3: bottom_left