# Data
path: /content/drive/My Drive/nic_project/datasets/name_det
train: images/train  # train images (relative to 'path')
val: images/val  # val images (relative to 'path')


# Classes
names:
  0: name1
  1: name2
  2: name3